[package]
name = "chain-replay-watchdog"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive", "env"] }
discv5 = "0.9.1"
eyre = "0.6.12"
kona-cli = { git = "https://github.com/thedevbirb/kona", branch = "lore/chore/unsafe-payloads" }
kona-disc = { git = "https://github.com/thedevbirb/kona", branch = "lore/chore/unsafe-payloads" }
kona-node-service = { git = "https://github.com/thedevbirb/kona", branch = "lore/chore/unsafe-payloads" }
kona-registry = { git = "https://github.com/thedevbirb/kona", branch = "lore/chore/unsafe-payloads" }
libp2p = "0.56.0"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = "0.7.16"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
