set quiet

suppress_output := env("QUIET", "true")
quiet := if suppress_output == "true" { "--quiet > /dev/null 2>&1 " } else { "" }

# Build the docker image from the corresponding `.Dockerfile`
build image *args:
    echo "Building {{image}}..."
    docker build -t local_based_{{image}} -f ./{{image}}.Dockerfile ../ {{args}} \
    {{quiet}}

save image dest:
    echo "Exporting {{image}}..."
    docker save local_based{{image}} | gzip > {{dest}}/based-{{image}}.tar.gz

build-portal: (build "portal")
build-registry: (build "registry")
build-gateway: (build "gateway")
build-txproxy: (build "txproxy")
build-metrics-exporter: (build "metrics-exporter" "--load")

[parallel]
all: build-portal build-registry build-gateway build-txproxy build-metrics-exporter

[parallel]
export-all dest: (save "portal" dest) (save "registry" dest) (save "gateway" dest) (save "txproxy" dest) (save "metrics-exporter" dest)

# Creates the docker network `name` if it doesn't already exist
create-network name="based_op_net":
    docker network inspect {{name}} > /dev/null 2>&1 || docker network create {{name}}
