[package]
name = "bop-sequencer"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bop-common.workspace = true
bop-pool.workspace = true

# alloy
alloy-rpc-types.workspace = true

# async
tokio.workspace = true
futures.workspace = true

revm-primitives.workspace = true
tracing.workspace = true

# networking
reqwest.workspace = true
