[package]
name = "bop-sequencer"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bop-common.workspace = true
bop-pool.workspace = true
bop-db.workspace = true

# alloy
alloy-rpc-types.workspace = true
alloy-provider.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true

# op alloy
op-alloy-consensus.workspace = true

# reth
reth-evm.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-consensus.workspace = true

# reth op
reth-optimism-evm.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-primitives.workspace = true
reth-optimism-consensus.workspace = true

# revm
revm-primitives.workspace = true
revm.workspace = true

# async
tokio.workspace = true
futures.workspace = true

tracing.workspace = true

# networking
reqwest.workspace = true
crossbeam-channel.workspace = true

# misc
thiserror.workspace = true

# tmp here so that the the compiler picks up the reth op crates
reth-optimism-node.workspace = true
reth-optimism-cli.workspace = true
