[package]
name = "bop-common"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
eyre.workspace = true
once_cell.workspace = true
chrono.workspace = true
quanta.workspace = true
directories.workspace = true
shared_memory.workspace = true

crossbeam-channel.workspace = true
