[workspace]
members = ["crates/*", "bin/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
rust-version = "1.83.0"
edition = "2021"
repository = "https://github.com/gattaca-com/preconf-base"

[workspace.dependencies]
pb-common = { path = "crates/common" }
