[package]
default-run = "bop-gateway"
edition.workspace = true
name = "bop-gateway"
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-provider.workspace = true
bop-common.workspace = true
bop-db.workspace = true
bop-rpc.workspace = true
bop-sequencer.workspace = true
clap.workspace = true
eyre.workspace = true
op-alloy-consensus.workspace = true
op-alloy-rpc-types.workspace = true
reqwest.workspace = true
revm-primitives.workspace = true
serde_json.workspace = true

serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[[bin]]
name = "bop-gateway"
path = "src/main.rs"
