[package]
name = "bop-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bop-common.workspace = true
bop-rpc.workspace = true
bop-simulator.workspace = true
bop-sequencer.workspace = true
bop-db.workspace = true
tokio.workspace = true
clap.workspace = true
reqwest.workspace = true
eyre.workspace = true
tracing.workspace = true
alloy-provider.workspace = true
alloy-eips.workspace = true
revm-primitives.workspace = true
reth-optimism-chainspec.workspace = true
