[workspace]
members = ["bin/*", "crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
repository = "https://github.com/gattaca-com/based-op"
rust-version = "1.85.0"
version = "0.1.0"

[workspace.dependencies]
alloy-consensus = "1.0.41"
alloy-eips = "1.0.41"
alloy-network = "1.0.41"
alloy-primitives = { version = "1.0.41", default-features = false, features = ["getrandom"] }
alloy-provider = "1.0.41"
alloy-rlp = "0.3.12"
alloy-rpc-types = { version = "1.0.41", features = ["engine", "mev"] }
alloy-signer = "1.0.41"
alloy-signer-local = "1.0.41"
alloy-transport = "1.0.41"
alloy-transport-http = "1.0.41"
auto_impl = "1.3.0"
axum = { version = "0.8.1", features = ["macros", "ws"] }

backtrace = "0.3.73"
bitflags = "2.6.0"
bop-common = { path = "crates/common" }
bop-db = { path = "crates/db" }
bop-metrics = { path = "crates/metrics" }
bop-pool = { path = "crates/pool" }
bop-rpc = { path = "crates/rpc" }
bop-sequencer = { path = "crates/sequencer" }
chrono = "0.4.23"
clap = { version = "4.5.27", features = ["derive", "env"] }
crossbeam-channel = "0.5.14"
directories = "5.0.1"
either = "1.15.0"
ethereum_ssz = "0.9.0"
eyre = "0.6.12"
futures = "0.3.31"
hickory-resolver = "=0.25.0-alpha.5"                                                                           # Use the exact version reth expects
http = "1.3.1"
hyper = "1.5.2"
indexmap = "2.12"
jsonrpsee = { version = "0.26", features = ["http-client", "jsonrpsee-client-transport", "macros", "server"] }
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
mio = { features = ["net", "os-poll"], version = "1.0.4" }
mio_httpc = { features = ["native"], version = "0.10.6" }
moka = "0.12.10"
op-alloy-consensus = { version = "0.22.0", default-features = false, features = ["k256"] }
op-alloy-flz = { version = "0.13.1", default-features = false }
op-alloy-network = "0.22.0"
op-alloy-rpc-types = "0.22.0"
op-alloy-rpc-types-engine = { version = "0.22.0", default-features = false, features = ["serde"] }
op-revm = "12.0.1"
parking_lot = "0.12.3"
paste = "0.1.18"
quanta = "0.12.3"
rand = "0.9.0"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
wyhash = "0.6.0"

reth-chain-state = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-chain-state" }
reth-chainspec = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-chainspec" }
reth-cli = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-cli" }
reth-consensus = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-consensus" }
reth-db = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-db" }
reth-db-api = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-db-api" }
reth-db-common = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-db-common" }
reth-engine-tree = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-engine-tree" }
reth-evm = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-evm" }
reth-execution-errors = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-execution-errors" }
reth-node-ethereum = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-node-ethereum", features = [
  "test-utils",
] }
reth-node-types = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-node-types" }
reth-optimism-chainspec = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-chainspec" }
reth-optimism-cli = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-cli" }
reth-optimism-consensus = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-consensus" }
reth-optimism-evm = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-evm" }
reth-optimism-forks = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-forks" }
reth-optimism-node = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-node" }
reth-optimism-payload-builder = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-payload-builder" }
reth-optimism-primitives = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-primitives" }
reth-optimism-txpool = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-optimism-txpool" }
reth-primitives = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-primitives" }
reth-primitives-traits = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-primitives-traits" }
reth-provider = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-provider", features = [
  "test-utils",
] }
reth-revm = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-revm" }
reth-rpc-builder = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-rpc-builder" }
reth-rpc-layer = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-rpc-layer" }
reth-stages-types = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-stages-types" }
reth-storage-api = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-storage-api" }
reth-storage-errors = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-storage-errors" }
reth-trie = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-trie" }
reth-trie-common = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-trie-common", features = [
  "test-utils",
] }
reth-trie-db = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-trie-db" }
reth-trie-parallel = { git = "https://github.com/gattaca-com/based-op-reth", rev = "b053849462eb48e61b24d965cfee59cead7f8a3b", package = "reth-trie-parallel" }

revm = { version = "31.0.1", features = ["optional_balance_check", "secp256k1", "std"], default-features = false }
revm-handler = "12.0.0"
revm-inspector = "12.0.1"
revm-interpreter = "29.0.1"
revm-primitives = { version = "21.0.2", features = ["std"], default-features = false }

rustc-hash = "2.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
shared_memory = "^0.12"
signal-hook = "0.3.17"
ssz_types = "0.11.0"
strum = "0.24"
strum_macros = "0.24"
tabwriter = "1.4.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.19"
tower = { version = "0.5", features = ["timeout"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt", "time"] }
tree_hash = "0.10"
tree_hash_derive = "0.10"
uuid = { version = "1.12.1", features = ["serde", "v4"] }

[profile.release-prod]
codegen-units = 1
debug = false
inherits = "release"
lto = true
opt-level = 3
split-debuginfo = "off"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.release-with-debug]
inherits = "dev"
opt-level = 3
