toolchain := "nightly"

toolchain:
  rustup toolchain install {{toolchain}} > /dev/null 2>&1

fmt: toolchain
  cargo +{{toolchain}} fmt

fmt-check: toolchain
  cargo +{{toolchain}} fmt --check

clippy: toolchain
  cargo +{{toolchain}} clippy --all-features --no-deps -- -D warnings

