{
 "title": "based-op",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions ingestion and inclusion throughput",
   "type": "timeseries",
   "description": "Displays the rate of ingestion and inclusion of transactions. Simulation error rate is overlaid to help surface issues with invalid state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(bop_gateway_tx_ingested_total[$__rate_interval])",
     "legendFormat": "Ingested TPS"
    },
    {
     "expr": "rate(bop_gateway_tx_included_total[$__rate_interval])",
     "legendFormat": "included TPS"
    },
    {
     "expr": "rate(bop_simulation_errors[$__rate_interval])",
     "legendFormat": "simulation errors per second"
    }
   ]
  },
  {
   "title": "Chain throughput (TPS)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bop_gateway_tps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chain throughput (MGas/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bop_gateway_m_gas_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last synced block",
   "type": "stat",
   "description": "Last block for which a `block_sync` process was triggered. If the sequencer is active, it is normal for it to not sync",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bop_block_sync_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sequencer state",
   "type": "stat",
   "description": "Sorting == good :) ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bop_sequencer_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last sorted block",
   "type": "stat",
   "description": "Last block number that was successfully sorted.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bop_sorting_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total frags committed",
   "type": "stat",
   "description": "Total amount of frags committed",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bop_sequencer_commit_frag_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulation requests and errors per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(bop_simulation_requests_sent[$__rate_interval])",
     "legendFormat": "simulation requests"
    },
    {
     "expr": "rate(bop_simulation_errors[$__rate_interval])",
     "legendFormat": "simulation errors"
    }
   ]
  },
  {
   "title": "Chain throughput (MGas/s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MGas/s" } },
   "targets": [
    { "expr": "bop_gateway_m_gas_s", "legendFormat": "mgas/s" }
   ]
  },
  {
   "title": "Blockchain TPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "bop_gateway_tps", "legendFormat": "tps" }
   ]
  },
  {
   "title": "Total blocks sorted",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "targets": [
    { "expr": "bop_build_stop_block_number", "legendFormat": "blocks sorted" }
   ]
  },
  {
   "title": "txpool memory size",
   "type": "timeseries",
   "description": "estimated size of transactions active in the txpool at any time",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bop_transaction_pool_memory_bytes",
     "legendFormat": "txpool memory bytes"
    }
   ]
  },
  {
   "title": "Sorting simulation time",
   "type": "timeseries",
   "description": "Total time spent on simulations per frag sequence (so, per L2 block)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "bop_gateway_sorting_sim_time", "legendFormat": "sim time" }
   ]
  },
  {
   "title": "Transactions per frag and block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "bop_gateway_block_tx_count", "legendFormat": "block tx count" },
    { "expr": "bop_frag_tx_count", "legendFormat": "frag tx count" }
   ]
  },
  {
   "title": "Gateway transaction sim time",
   "type": "timeseries",
   "description": "Time it takes for the gateway to simulate any transaction",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bop_simulation_latency_ms{quantile=\"0.5\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "bop_simulation_latency_ms{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Gateway commit block duration",
   "type": "timeseries",
   "description": "Time it takes for the gateway to commit a block (including state root calc)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bop_gateway_commit_block_duration_ms{quantile=\"0.5\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "bop_gateway_commit_block_duration_ms{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "bop_gateway_commit_block_duration_ms{quantile=\"0.999\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Frags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Gas used per frag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Gas" } },
   "targets": [
    { "expr": "bop_frag_gas_used", "legendFormat": "gas used per frag" }
   ]
  },
  {
   "title": "Transactions per frag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    { "expr": "bop_frag_tx_count", "legendFormat": "transactions per frag" }
   ]
  },
  {
   "title": "Best order value per frag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    { "expr": "bop_frag_best_order_value", "legendFormat": "best order value per frag" }
   ]
  },
  { "title": "Follower based node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "OP geth head block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_block", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "OP geth safe head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_safe", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "OP geth finalized head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_finalized", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "OP Geth engine failures",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_duration_engine_newFragV0_failure_count",
     "legendFormat": "engine_newFragV0 failures"
    },
    {
     "expr": "rpc_duration_engine_envV0_failure_count",
     "legendFormat": "engine_envV0 failures"
    },
    {
     "expr": "rpc_duration_engine_sealFragV0_failure_count",
     "legendFormat": "engine_sealFragV0 failures"
    }
   ]
  },
  {
   "title": "OP node sequencing errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_sequencing_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP node peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OP node latency to block tags",
   "type": "timeseries",
   "description": "Displays the time passed for specific block tags to update. E.g. \"the finalized L1 head is 15 minutes from now\"",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "op_node_default_refs_latency", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "OP node L1 reorgs detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_l1_reorg_depth_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP geth peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "OP node based_ engine requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "op_node_default_rpc_server_request_duration_seconds_bucket{method=\"based_newFrag\", le=\"1.0\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "op_node_default_rpc_server_request_duration_seconds_bucket{method=\"based_sealFrag\", le=\"1.0\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "op_node_default_rpc_server_request_duration_seconds_bucket{method=\"based_env\", le=\"1.0\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "OP geth engine_newFrag processing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "engine_frag_new{quantile=\"0.5\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "engine_frag_new{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "engine_frag_new{quantile=\"0.999\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "OP geth engine_sealFrag processing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "engine_frag_seal{quantile=\"0.5\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "engine_frag_seal{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "engine_frag_seal{quantile=\"0.999\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "OP geth engine_envV0 processing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "engine_frag_env{quantile=\"0.5\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "engine_frag_env{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "engine_frag_env{quantile=\"0.999\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Metrics collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "metrics events processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    { "expr": "bop_metric_events_per_second", "legendFormat": "metrics events/s" }
   ]
  }
 ]
}