[package]
edition.workspace = true
name = "based-portal"
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
bop-common.workspace = true
clap.workspace = true
eyre.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
op-alloy-rpc-types-engine.workspace = true
reqwest.workspace = true
reth-rpc-layer.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
