[package]
edition.workspace = true
name = "bop-timekeeper"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bitflags = "2.6.0"
bop-common.workspace = true
crossterm = "0.28.1"
ratatui = "0.28.1"
rgb = "0.8.50"
textplots = "0.8.6"
tracing.workspace = true
