services:
  based-metrics-exporter:
    image: ghcr.io/chainbound/based-op/metrics-exporter:latest-amd64 # arm64 also available. TODO: make cross-platform
    container_name: based-metrics-exporter
    restart: unless-stopped
    environment:
      - RUST_LOG=${BOP_REPLAY_RUST_LOG:-}
    ports:
      - ${BOP_REPLAY_METRICS_EXPORTER_PORT}:${BOP_REPLAY_METRICS_EXPORTER_PORT}
    volumes:
      - /tmp:/tmp
      - /dev/shm:/dev/shm
    command:
      - "--port=${BOP_REPLAY_METRICS_EXPORTER_PORT}"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - ${BOP_REPLAY_PROMETHEUS_PORT}:${BOP_REPLAY_PROMETHEUS_PORT}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.listen-address=0.0.0.0:${BOP_REPLAY_PROMETHEUS_PORT}"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - ${BOP_REPLAY_GRAFANA_PORT}:${BOP_REPLAY_GRAFANA_PORT}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SERVER_HTTP_PORT=${BOP_REPLAY_GRAFANA_PORT}
      - GF_SECURITY_ADMIN_USER=based-op
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashboard.json
      - BOP_REPLAY_PROMETHEUS_PORT=${BOP_REPLAY_PROMETHEUS_PORT}
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
