[package]
name = "reth"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
tracing.workspace = true
bop-common.workspace = true
op-alloy-rpc-types.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
oneshot.workspace = true
reth_optimism_evm.workspace = true
reth_revm.workspace = true
revm.workspace = true

