[package]
name = "bop-mux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bop-common.workspace = true

alloy-primitives.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
op-alloy-rpc-types-engine.workspace = true
alloy-rpc-types.workspace = true
uuid.workspace = true
jsonrpsee.workspace = true
thiserror.workspace = true
eyre.workspace = true
clap.workspace = true
reth-rpc-layer.workspace = true
tower.workspace = true
hyper.workspace = true
futures.workspace = true
