[package]
name = "bop-mux"
version = "0.1.0"
edition = "2021"

[dependencies]
bop-common.workspace = true

tokio.workspace = true
axum.workspace = true
tracing.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
op-alloy-rpc-types-engine.workspace = true
alloy-rpc-types.workspace = true
eyre.workspace = true
